/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Luman (https://sketchfab.com/luman_models)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-binocular-2544cfd4cb5e44d5b02a42ebd28b367d
Title: Low Poly Binocular
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Binocular(props) {
  const { nodes, materials } = useGLTF('/models/low_poly_binocular-transformed.glb')
  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.rotation.y = Math.PI + Math.sin(state.clock.elapsedTime * .75) * .25;
  })

  return (
    <group {...props} dispose={null} ref={modelRef}
    position={[0,0.5,0]} scale={[2,2,2]} rotation={[.55,0,0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body_low__0.geometry}
        material={materials['Scene_-_Root']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/low_poly_binocular-transformed.glb')