/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/book.glb --transform 
Files: public/models/book.glb [11.61KB] > /Users/simonyong/Documents/GitHub/Developer-Portfolio/book-transformed.glb [3.07KB] (74%)
Author: Eric Fan (https://sketchfab.com/ericfan1992)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/book-fc1b43e332d147edb7dca8f89cffa4d7
Title: Book
*/

"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Book(props) {
  const { nodes, materials } = useGLTF('/models/book-transformed.glb')
  const modelRef = useRef()
  useFrame((state, delta, xrFrame) => {
    // This function runs at the native refresh rate inside of a shared render-loop
    modelRef.current.position.y = -.25 + Math.sin(state.clock.elapsedTime) * .15;
  })
  return (
    <group {...props} ref={modelRef} dispose={null} 
    position={[-1,0,0]} scale={[2.5,3,2.5]} rotation={[.5,.5,0]}
    >
      <mesh geometry={nodes.Architexture_0.geometry} material={materials.Architexture} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Architexture_1.geometry} material={materials.Bookpage} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/book-transformed.glb')
